### ISSUE TITLE
`useSendTransaction` does not update its state on error

### ISSUE THREAD

**Issue by filoozom** [swarmcity/boardwalk-ts#17]
When calling `useSendTransaction`, the password modal shows up as expected, but if the transaction results in an error (for example due to unsufficient funds), its state (`isLoading`, `isError`, `error`, ...) is not updated, which results in infinite loading.

The thrown error (probably not catched when it should?):

```
Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f86a05808459682f008459682f1082520894f76c4b9fbb9fcc2c4c1cdfb11bd6e708ccc66e338080c080a01e137bd2e588741c9a4f9a0c6996690a67ffc5f923ad2e35b6a92c8021752c88a012352598605fc52f08e263c10c8b492646a645177f3613c5e56f9330f6857958\"],\"id\":51,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://eth-goerli.alchemyapi.io/v2/GPR_qF9l_vj-iDb1Kdg3cjDBB-ktJ7Lt"}, method="sendTransaction", transaction="0x02f86a05808459682f008459682f1082520894f76c4b9fbb9fcc2c4c1cdfb11bd6e708ccc66e338080c080a01e137bd2e588741c9a4f9a0c6996690a67ffc5f923ad2e35b6a92c8021752c88a012352598605fc52f08e263c10c8b492646a645177f3613c5e56f9330f6857958", code=INSUFFICIENT_FUNDS, version=providers/5.6.8)
    at Logger.makeError (index.ts:261:28)
    at Logger.throwError (index.ts:273:20)
    at checkError (json-rpc-provider.ts:98:16)
    at JsonRpcProvider.<anonymous> (json-rpc-provider.ts:603:20)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:20:1)
```

I'm guessing this is on `wagmi`, haven't investigated that much yet though.

**Comment by filoozom** [comment]
Fixed by replacing `preact` with `react`.
